### ISSUE TITLE
Bug: (Might be just me) Sign in after migration from 02x requires 2FA via email.

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/mastodon-startos#13]
This email doesn't come. The UN/Password combo are definitely correct.

![Screen Shot 2022-01-18 at 6 18 50 PM](https://user-images.githubusercontent.com/45926711/150051299-910b1a82-0bb8-4161-b4d0-f9d278bb514d.png)

**Comment by chrisguida** [comment]
@BitcoinMechanic can you try installing from latest beta? Now that I'm looking at this screenshot I think I get why I haven't been able to recreate.
