### ISSUE TITLE
Issues with Brave tor

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/mastodon-startos#2]
Signing up/logging in renders a page that asks if cookies are being blocked.

A naive messing with the cookie settings don't seem to reveal anything. Filing here for later.

**Comment by ChuckleSan** [comment]
Same problem here, error message is "Security verification failed. Are you blocking cookies?"

**Comment by dr-bonez** [comment]
Mastodon needs to set http onions as a secure context
